### ISSUE TITLE
Question about unpredictable behavior that upgrading the page

### ISSUE THREAD

**Issue by viktoryou** [riscv-non-isa/riscv-iommu#381]
From the spec,
> In a conventional TLB design, it is possible for multiple entries to match a single address if, for example, a page is upgraded to a larger page without first clearing the original non-leaf PTE’s valid bit and executing an IOTINVAL.VMA or IOTINVAL.GVMA as applicable with AV=0. In this case, a similar remark applies: it is unpredictable whether the old non-leaf PTE or the new leaf PTE is used, but the behavior is otherwise well defined.

About this unpredictable behavior, would the usage of whether old non-leaf PTE or the new leaf PTE still matter? In other words, when an implementation uses another value (possibly a mixture of old non-leaf PTE and the new leaf PTE due to multi-hit of TLB), would it violates the intention of the spec?

**Comment by ved-rivos** [comment]
Consider a 2 MB memory region starting at PA=X. When this region was mapped using 4K pages there are 512 PTEs where first PTE points to X, second to X+4K, and so on. Software can upgrade this to a 2M page using a single PTE mapping which points to X. Now if software did not do a TLB invalidation then hardware may use one of the cached old 512 4K PTEs or the new 2M PTE. As long as both provide same permissions and point to the same memory region whether hardware uses the old 4K PTE or new 2M PTE should lead to same result. 

> In other words, when an implementation uses another value (possibly a mixture of old non-leaf PTE and the new leaf PTE due to multi-hit of TLB), would it violates the intention of the spec?

By mixture I assume your hardware on a multi-hit ORs the PTE entries? If so that would violate the specification. Hardware should use either the old PTE or the new PTE but any other answer is not allowed. If your implementation uses one TLB structure to hold both 4K and 2M entries and is fully associative then you could prioritize the lowest numbered hit or the highest numbered hit or any one of the hits - but one. If you use a set associative structure and you search in the set corresponding to 4K size and set corresponding to 2M size and hit in both then you can choose one or other - for example you may prioritize 2M set over 4K set. If you use separate TLBs for 4K and 2M sizes and hit in both then again you could choose one over other - for example you may prioritize 2M over 4K.

**Comment by viktoryou** [comment]
> As long as both provide same permissions and point to the same memory region whether hardware uses the old 4K PTE or new 2M PTE should lead to same result.

I found it from the IOMMU while not in the Privilege spec:
> When promoting and/or demoting page sizes, software must ensure that the original and new PTEs have identical permission and memory type attributes and the physical address that is determined as a result of translation using either the original or the new PTE is otherwise identical for any given input. The only PTE update supported by the IOMMU without first clearing the V bit in the original PTE and executing a appropriate IOTINVAL command is to do a page size promotion or demotion. The behavior of the IOMMU if other attributes are changed in this fashion is implementation defined.

Would the constraint (identical permission/memory type attributes/physical address) also get applied in the context of the Privilege spec, since they share the virtual memory?

Further, if the software forgot to first clear the V bit in the original PTE or execute an appropriate IOTINVAL command when updating PTE in an unsupported manner, it seems that hardware should use either the old translation or the new translation, analogously, to follow the spec:
> In particular, if a leaf PTE is modified but a subsuming IOTINVAL is not executed, either the old translation or the new translation will be used, but the choice is unpredictable. The behavior is otherwise well-defined.

Am I right?

**Comment by ved-rivos** [comment]
> Would the constraint (identical permission/memory type attributes/physical address) also get applied in the context of the Privilege spec, since they share the virtual memory?

Its a common sense guideline. We dont have too many guidelines in the Priv. spec but the guideline from IOMMU will follow if they share a page table.

>Am I right?

Yes
